# Generated by Django 4.2 on 2024-11-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.FileField(blank=True, null=True, upload_to='invitation')),
                ('venue', models.CharField(max_length=100)),
                ('event_time', models.CharField(max_length=100)),
            ],
        ),
    ]
