# Generated by Django 4.2 on 2024-11-23 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tbl_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_event_std_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_event_detail', to='myapp.tbl_event')),
                ('ref_std', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_studnet_detail', to='myapp.tbl_student')),
            ],
        ),
    ]
