# Generated by Django 4.2 on 2024-11-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tbl_event_std_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_event',
            name='guest_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbl_event',
            name='guest_profile',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
