# Generated by Django 4.2 on 2024-11-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_tbl_event_guest_name_tbl_event_guest_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_event',
            name='guest_profile',
            field=models.FileField(null=True, upload_to='guest_profile'),
        ),
    ]
