# Generated by Django 4.2 on 2024-11-23 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_tbl_event_guest_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_student',
            old_name='roll_number',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='tbl_student',
            old_name='year',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='tbl_student',
            old_name='address',
            new_name='regno',
        ),
        migrations.AddField(
            model_name='tbl_student',
            name='ref_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_event', to='myapp.tbl_event'),
        ),
        migrations.DeleteModel(
            name='tbl_event_std_detail',
        ),
    ]
