# Generated by Django 4.2 on 2024-11-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_roll_number_tbl_student_college_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_student',
            name='ref_event',
        ),
        migrations.DeleteModel(
            name='tbl_event',
        ),
        migrations.DeleteModel(
            name='tbl_student',
        ),
    ]
