# Generated by Django 4.2 on 2024-11-23 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0007_remove_tbl_student_ref_event_delete_tbl_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.FileField(blank=True, null=True, upload_to='invitation')),
                ('venue', models.CharField(max_length=100)),
                ('event_time', models.CharField(max_length=100)),
                ('guest_name', models.CharField(max_length=100, null=True)),
                ('guest_profile', models.FileField(null=True, upload_to='guest_profile')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('regno', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=100)),
                ('ref_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_event_detail', to='myapp.tbl_event')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('ref_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_event_view', to='myapp.tbl_event')),
                ('ref_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_student_detail', to='myapp.tbl_student')),
            ],
        ),
    ]
